Update dotnet.yml

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -26,3 +26,26 @@ jobs:
       run: dotnet build --no-restore
     - name: Test
       run: dotnet test --no-build --verbosity normal
+    - name: Install Connector Validator
+      run: dotnet tool install -g Skyline.DataMiner.CICD.Tools.Validator
+    
+    - name: Run Connector Validator
+      run: dataminer-validator validate-protocol-solution --solution-path "${{ github.workspace }}" --output-directory "${{ github.workspace }}" --output-file-name "validateResults" 
+    
+    - name: Archive Results
+      if: success()
+      uses: actions/upload-artifact@v4
+      with:
+        name: validateResults
+        path: ${{ github.workspace }}/validateResults.json
+    
+    - name: Quality Gate
+      run: |
+        json=$(cat "${{ github.workspace }}/validateResults.json")
+        critical=$(echo "$json" | jq -r '.CriticalIssueCount')
+        major=$(echo "$json" | jq -r '.MajorIssueCount')
+    
+        if [ "$critical" != "0" ] || [ "$major" != "0" ]; then
+          echo "Error: CriticalIssueCount or MajorIssueCount is not 0"
+          exit 1
+        fi
